export const getRegion = (v: string) => /^<?.*region[^:]*:([^\n]+)<+?/im.exec(v);
export const getAddress = (v: string): RegExpExecArray | null => /^<?.*address[^:]*:.*?(f\d[0-9A-Za-z]+)/im.exec(v);
export const getName = (v: string) => /^<?.*name[^:]*:([^\n]{0,80})<+?/im.exec(v);
export const getOrganization = (v: string) => /^.*?organization.{0,5}?: *(?:[\s"'\\*])*([\d\w _\-(),./]+)(?:[\s\n\r]\(<\\)*(?:[\s\n\r"'\\])*/im.exec(v);
export const getWebsiteAndSocial = (v: string) => /^<?.*website.{0,3}social[^:]*:([^\n\r]+)<+?/im.exec(v);
export const getApprovedAddress = (v: string) => /approved.*[\r\n]*.*address.*[\r\n]*.*\s+(f[0-9]+[^\r]+)/im.exec(v);
export const regionIsAfrica = (v: string) => /^\s*(Africa)\s*$/im.test(v);
export const regionIsAsiaNotGreaterChina = (v: string) => /^\s*(Asia.minus.GCN)\s*$/im.test(v);
export const regionIsEurope = (v: string) => /^\s*(Europe|EU)\s*$/im.test(v);
export const regionIsGreaterChina = (v: string) => /^\s*(Asia.GCN|GCN.Asia|China|Greater.China)\s*$/im.test(v);
export const regionIsNorthAmerica = (v: string) => /^\s*(n\/a|North.America|NA)\s*$/im.test(v);
export const regionIsOceania = (v: string) => /^\s*(Oceania)\s*$/im.test(v);
export const regionIsSouthAmerica = (v: string) => /^\s*(South.America)\s*$/im.test(v);
export const regionIsGlobal = (v: string) => /^\s*(Global)\s*$/im.test(v);
export const regionIsOther = (v: string) => /^\s*(Other)\s*$/im.test(v);
export const isValidAddress = (v: string) => /^f[a-zA-Z0-9]+$/im.test(v);
